---
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

jobs:
  build:
    docker:
      - image: golang:1.17-alpine
        <<: *docker-auth
    steps:
      - run:
          name: Install system dependencies
          command: |
            apk add -U zip make git
      - checkout
      - run:
          name: Get dependencies
          command: |
            go mod download
      - run:
          name: Build
          command: |
            export GOOS=linux
            export GOARCH=amd64 $(BUILD_CMD) -o $(OUTPUT)
            go build -tags netgo --ldflags "-extldflags '-static' -X main.GitSHA=${GIT_SHA}" -o bin/confd .

      #- run:
      #    name: Prepare dirs
      #    command: |
      #      mkdir -p src/github.com/connectedservices
      #- checkout:
      #    path: src/github.com/connectedservices/confd
      #- run:
      #    name: Build Go package
      #    command: |
      #      cd src/github.com/connectedservices/confd
      #      make build

      #- persist_to_workspace:
      #    root: src/github.com/connectedservices/confd/
      #    paths:
      #      - "bin/*"

  publish:
    docker:
      - image: alpine:3.15
        <<: *docker-auth
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add -U aws-cli
      - attach_workspace:
          at: ./
      - run:
          name: Publish artifact
          command: |
            if [ -n "${CIRCLE_TAG+x}" ]; then
              VERSION=${CIRCLE_TAG}
            else
              VERSION=sha-${CIRCLE_SHA1::7}
            fi
            aws s3 cp bin/confd "s3://${ARTIFACTS_BUCKET}/confd/${VERSION}/confd"

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
      - approve_publish:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - publish:
          context: org-global
          requires:
            - approve_publish
          filters:
            branches:
              ignore:
                - master
      - publish:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: master
